name: BrettVincent
favicon: null
layout_spectrum: 0.9854079880751669
typography_spectrum: 0.10038489638827741
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors: []
  brandStrength: 0.47192462207749486
  lightness: 0.2662051620427519
  saturation: 0.10310945683158934
  rhythmicContrast: 0.7385064507834613
purpose: []
