name: BrettVincent
favicon: null
layout_spectrum: 0.9854079880751669
typography_spectrum: 0.33821
title: Comedy
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#f5f5f5'
    - '#010101'
    - '#af2d19'
    - '#444d45'
    - '#a3a128'
  brandStrength: 0.47192462207749486
  lightness: 0.25
  saturation: 0.625
  rhythmicContrast: 0.75
purpose: []
